# Generated by Django 4.1.7 on 2023-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('avatar_url', models.CharField(default='https://uploads-ssl.webflow.com/6198a2e43048192ebafec2cc/63d221403d9cfe4ced015d95_yxRQH9s6VEU6gldnFhl3PDigUW31MIHSSqavg8i9s24.png', max_length=15)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
