# Generated by Django 4.1.7 on 2023-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.CharField(default='https://uploads-ssl.webflow.com/6198a2e43048192ebafec2cc/63d221403d9cfe4ced015d95_yxRQH9s6VEU6gldnFhl3PDigUW31MIHSSqavg8i9s24.png', max_length=15)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='https://uploads-ssl.webflow.com/6198a2e43048192ebafec2cc/63d221403d9cfe4ced015d95_yxRQH9s6VEU6gldnFhl3PDigUW31MIHSSqavg8i9s24.png', max_length=150),
        ),
    ]
